authors/urls.py
from django.urls import path
from . import views


app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='create'),
]

project/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, documente_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documente_root=settings.STATIC_ROOT)

projeto/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, documente_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, documente_root=settings.STATIC_ROOT)

recipes/urls.py
from . import views
from django.urls import path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name="recipes-home"),
    path('recipes/search/', views.search, name="search"),
    path('recipes/category/<int:category_id>/', views.category, name="recipes-category"), # noqa 501
    path('recipe/<int:id>/', views.recipe, name="recipes-recipe"),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        default=None,
    )

    def __str__(self):
        return self.title

authors/forms.py
from django import forms
from django.contrib.auth.models import User


def add_attr(field, attr_name, attr_new_val):
    existing = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing} {attr_new_val}'.strip()


def add_placeholder(field, placeholder_val):
    field.widget.attrs['placeholder'] = placeholder_val
    add_attr(field, 'placeholder', placeholder_val)


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'Your username')
        add_placeholder(self.fields['email'], 'Your e-mail')
        add_placeholder(self.fields['first_name'], 'Ex.: John')
        add_placeholder(self.fields['last_name'], 'Ex.: Doe')
        add_attr(self.fields['username'], 'css', 'a-css-class')

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Your password'
        }),
        error_messages={
            'required': 'Password must not empty'
        },
        help_text=(
            'Password must have at least one uppercase letter, '
            'one lowercase letter and one number. The length should be'
            'at least 8 chatacters.'
        )
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat your password'
        })
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

        labels = {
            'username': 'Username',
            'first name': 'First name',
            'last name': 'Last name',
            'email': 'E-mail',
            'password': 'Password',
        }
        help_texts = {
            'email': 'The e-mail must be valid'
        }
        error_messages = {
            'username': {
                'required': 'This field must not be empty',
            }
        }
        widgets = {
            'first_name': forms.TextInput(attrs={
                'placeholder': 'Type your username here'
            }),
            'password': forms.PasswordInput(attrs={
                'placeholder': 'Type your password here'
            })
        }

authors/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from .forms import RegisterForm


def register_view(request):
    register_form_data = request.session.get('register_from_data', None)
    form = RegisterForm(register_form_data)
    return render(request, 'authors/pages/register_view.html', {
        'form': form,
    })


def register_create(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    return redirect('authors:register')

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http.response import Http404
from django.db.models import Q
from utils.pagination import make_pagination
from .models import Recipe

import os

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


def home(request):
    recipes = Recipe.objects.filter(
        is_published=True
        ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(
        category__id=category_id,
        is_published=True
        ).order_by('-id')
    )

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/''category.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': f'{recipes[0].category.name} - Category |'
    })


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
        })


def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'Search for "{search_term}" |',
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}',
    })

authors/templates/authors/pages/register_view.html
{% extends "global/base.html" %}

{% block title %}Register |{% endblock title %}

{% block content %}

    <div class="main-content center container">
        <h2>Register {{ request.session.number }}</h2>
    </div>

    <div class="main-content container">
        <form action="{% url "authors:create" %}" method="POST">
            {% csrf_token %}
            <div class="form-content form-content-gird">
                {% for field in form %}
                    <div class="form-gruop">
                        <label for="{{ field.id_for_label }}">
                            {{field.label}}
                        </label>
                        {{field}}

                        {% if field.help_text %}
                            <p class="help_text">{{ field.help_text }}</p>
                        {% endif %}

                        {{ field.errors }}
                    </div>

                {% endfor %}
            </div>
            <div class="form-content form-content-grid">
                <div class="form-group">
                <button type="submit">Send</button>
            </div>
        </form>
    </div>

{% endblock content %}

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}


{% block title %} {{ title }}{% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% endfor %}
</div> 
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}


{% block title %}Home |{% endblock title %}

{% block content %}
{% include 'recipes/partials/messages.html' %}

<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include "recipes/partials/recipe.html" %}
    {% empty %}
        <div class="center">
            <h1> No recipes found </h1>
        </div>
    {% endfor %}
</div> 
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %} {{ recipe.title }} |{% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}


{% block title %} {{ page_title }} {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include "recipes/partials/recipe.html" %}
    {% empty %}
        <div class="center">
            <h1> No recipes found </h1>
        </div>
    {% endfor %}
</div> 
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Otávio Miranda</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- update any styles .js files you have linked -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- font-google -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "global\css\styles.css" %}">
    <link rel="stylesheet" href="{% static "global\css\global-styles.css" %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href=" {% url "recipes-home" %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class='main-logo-text'>
                    Recipes
                </span>
            </a>
        </h1>
    </div>

</header>

recipes/templates/recipes/partials/messages.html
{% if messages %}
    <div class="main-content center container messages-container">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

recipes/templates/recipes/partials/pagination.html
{% if recipes.has_other_pages %}
    <div class="container pagination">
        <div class="pagination-content">

            {% if pagination_range.first_page_out_of_range %}
                <a class="page-link page-item" href="?page=1{{ additional_url_query }}">1</a>
                <span class="page-item">...</span>
            {% endif %}

            {% for page in pagination_range.pagination %}
                {% if pagonation_range.current_page == page %}
                    <a class="page-current page-link page-item " href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                {% else %}
                    <a class="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
                {% endif %}
            {% endfor %}

            {% if pagination_range.last_page_out_of_range %}
                <span class="page-item">...</span>
                <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
            {% endif %}
        </div>
    </div>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes-recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url "recipes-recipe" recipe.id %}">{{ recipe.title }}</a>
        </h2>
    </div>
    
    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes-category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>
    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url "recipes-recipe" recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}
    {% if is_detail_page is True %}
        <div class="preparation-steps"> 
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class='container'>
        <form action="{% url 'search' %}" method='GET' class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>